- build.xml
> [ENGOPS-1132] - Patched marketplace build

- marketplace-di/src/main/java/org/pentaho/marketplace/di/plugin/MenuHandler.java
Depends on pentaho/pentaho-kettle#1732
> [MARKET-308] Open marketplace tab without address bar

- marketplace-ba/pom.xml
- marketplace-ba/src/main/java/org/pentaho/marketplace/domain/services/BaPluginService.java
- marketplace-ba/src/test/java/org/pentaho/marketplace/domain/services/BaPluginServiceTest.java
- pom.xml
- Changed the imports
- Added the dependency for springframework and spring
security
> [BACKLOG-10623] Upgraded the spring framework and spring security

- marketplace-ba/src/main/java/org/pentaho/telemetry/BaPluginTelemetry.java
- marketplace-core/src/main/java/org/pentaho/marketplace/domain/model/entities/serialization/MarketplaceXmlSerializer.java
- marketplace-core/src/main/java/org/pentaho/marketplace/domain/model/entities/serialization/jaxb/JAXBMarketplaceXmlSerializer.java
- marketplace-core/src/main/java/org/pentaho/marketplace/util/XmlParserFactoryProducer.java
- marketplace-di/src/main/java/org/pentaho/marketplace/domain/services/DiPluginService.java
- marketplace-di/src/main/java/org/pentaho/telemetry/DiPluginTelemetry.java
@mbatchelor, @pamval, could you please take a look?
> [PPP-3506] - XXE Security Vulnerability in xml parsers

- pom.xml
> [BACKLOG-15428] Update parent pom to 7.1-SNAPSHOT

- .gitignore
- README.md
@pentaho/2-1b @pminutillo Please review
> [BACKLOG-15557] adding README.md file

- marketplace-di/src/main/resources/web/main.html
@pentaho/millenniumfalcon please review
> [BACKLOG-19912] changed call to require-init to webcontext

- marketplace-ba/pom.xml
- pom.xml
WARNING!  FOR MERGE BY PROCESS ONLY PLEASE!
> [ENGOPS-1757] version name consolidation

- marketplace-ba/pom.xml
- marketplace-di/pom.xml
- pom.xml
@pentaho/x-wing 
Depends on https://github.com/pentaho/maven-parent-poms/pull/53
> [ENGOPS-2977] Updating build helper maven plugin

- pom.xml
Needs https://github.com/pentaho/pentaho-osgi-bundles/pull/286.
@pentaho/millenniumfalcon please review.
> [BACKLOG-24937] Upgraded angular to 1.5.8

- pom.xml
> [BACKLOG-27567] Centralize org.osgi dependencies management

- pom.xml
> [BACKLOG-27569] Centralize pax-web dependency management

- pdi-marketplace-assembly/src/main/feature/feature.xml
- pentaho-marketplace-assembly/src/main/feature/feature.xml
- pom.xml
Needs https://github.com/pentaho/maven-parent-poms/pull/109.
@graimundo
> [BACKLOG-27565] Centralize CXF dependency version

- marketplace-di/src/main/resources/web/css/globalCrystal.css
> [BACKLOG-28362] Remove angular directives. No longer exists in common-ui

- marketplace-ba/pom.xml
- marketplace-di/pom.xml
> [BACKLOG-29567] Prevent transitives forcing requirement of java.xml.bind 2.3

- marketplace-core/src/main/resources/web/js/services/categoryService.js
@pentaho/millenniumfalcon please review
> [PPP-4413] Fix to unhandled exception on marketplace Category Service

- marketplace-core/src/main/resources/web/js/services/categoryService.js
- marketplace-core/src/main/resources/web/package.json
- pdi-marketplace-assembly/src/main/feature/feature.xml
- pentaho-marketplace-assembly/src/main/feature/feature.xml
- pom.xml
@pentaho/millenniumfalcon
/cc: @pentaho/r2d2
> [PPP-4413] Use of vulnerable component - Angular.js v1.5.8

- marketplace-ba/src/test/java/org/pentaho/marketplace/domain/services/BaPluginServiceTest.java
- pom.xml
This commit is a cherry-pick from master b1d18d74
> [SP-6179] [PPP-4654] Get commons-io version from parent pom

- marketplace-ba/src/main/java/org/pentaho/telemetry/BaPluginTelemetry.java
- marketplace-core/pom.xml
- marketplace-core/src/main/java/org/pentaho/marketplace/domain/model/entities/serialization/MarketplaceXmlSerializer.java
- marketplace-core/src/main/java/org/pentaho/marketplace/domain/model/entities/serialization/jaxb/JAXBMarketplaceXmlSerializer.java
- marketplace-core/src/main/java/org/pentaho/marketplace/util/XmlParserFactoryProducer.java
- marketplace-di/src/main/java/org/pentaho/marketplace/domain/services/DiPluginService.java
- marketplace-di/src/main/java/org/pentaho/telemetry/DiPluginTelemetry.java
[REVERT]-BACKLOG-36134-Consolidate Redundant Secure XML Parsing code
> [REVERT]-BACKLOG-36134-Consolidate Redundant Secure XML Parsing code

- marketplace-core/pom.xml
- marketplace-core/src/main/java/org/pentaho/marketplace/domain/model/entities/PluginVersion.java
- marketplace-core/src/main/java/org/pentaho/marketplace/domain/model/entities/serialization/jaxb/JAXBMarketplaceXmlSerializer.java
- marketplace-core/src/main/java/org/pentaho/marketplace/domain/model/entities/serialization/jaxb/dto/Category.java
- marketplace-core/src/main/java/org/pentaho/marketplace/domain/model/entities/serialization/jaxb/dto/DevelopmentStage.java
- marketplace-core/src/main/java/org/pentaho/marketplace/domain/model/entities/serialization/jaxb/dto/DevelopmentStageLane.java
- marketplace-core/src/main/java/org/pentaho/marketplace/domain/model/entities/serialization/jaxb/dto/Market.java
- marketplace-core/src/main/java/org/pentaho/marketplace/domain/model/entities/serialization/jaxb/dto/MarketEntryType.java
- marketplace-core/src/main/java/org/pentaho/marketplace/domain/model/entities/serialization/jaxb/dto/ObjectFactory.java
- marketplace-core/src/main/java/org/pentaho/marketplace/domain/model/entities/serialization/jaxb/dto/Version.java
- marketplace-core/src/main/java/org/pentaho/marketplace/domain/model/entities/serialization/jaxb/dto/VersionList.java
- marketplace-core/src/main/java/org/pentaho/marketplace/endpoints/MarketplaceService.java
- marketplace-core/src/main/java/org/pentaho/marketplace/endpoints/dtos/entities/PluginDTO.java
- marketplace-core/src/main/java/org/pentaho/marketplace/endpoints/dtos/entities/PluginVersionDTO.java
- marketplace-core/src/main/java/org/pentaho/marketplace/endpoints/dtos/responses/IterablePluginOperationResultDTO.java
- marketplace-core/src/main/java/org/pentaho/marketplace/endpoints/dtos/responses/StringOperationResultDTO.java
- marketplace-core/src/main/java/org/pentaho/marketplace/endpoints/dtos/responses/base/OperationResultDTO.java
- marketplace-core/src/main/java/org/pentaho/marketplace/endpoints/dtos/responses/base/StatusMessageDTO.java
- marketplace-di/pom.xml
- marketplace-di/src/main/java/org/pentaho/marketplace/util/web/HttpContext.java
- marketplace-di/src/main/java/org/pentaho/marketplace/util/web/HttpService.java
- marketplace-di/src/main/java/org/pentaho/marketplace/util/web/MarketplaceHttpContext.java
- marketplace-di/src/main/java/org/pentaho/marketplace/util/web/NamespaceException.java
- pom.xml
[BACKLOG-42755]-Upgrading marketplace from Java EE to Jakarta EE
[BACKLOG-42755]: https://hv-eng.atlassian.net/browse/BACKLOG-42755?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BACKLOG-42755]-Upgrading marketplace from Java EE to Jakarta EE

- marketplace-core/pom.xml
- marketplace-core/src/test/java/org/pentaho/marketplace/domain/model/entities/serialization/MarketplaceXmlSerializerTest.java
[BACKLOG-43098]-Fixing broken testcases as part of tomcat upgradation
[BACKLOG-43098]: https://hv-eng.atlassian.net/browse/BACKLOG-43098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BACKLOG-43098]-Fixing broken testcases as part of tomcat upgradation

- marketplace-core/pom.xml
[BACKLOG-43209]-OSGi Assembly Issues
[BACKLOG-43209]: https://hv-eng.atlassian.net/browse/BACKLOG-43209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BACKLOG-43209]-OSGi Assembly Issues
